# используем язык java. Travis CI поддерживает также и другие языки.
language:
         java
jdk:
    openjdk11

services:
  - postgresql

before_install:
  - psql -c "ALTER USER postgres WITH PASSWORD 'password';" -U postgres
  - psql -c 'create database tracker;' -U postgres
  - psql -c 'create database webstore;' -U postgres
  - psql -c 'create database cinema;' -U postgres

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - CODECOV_TOKEN="cd8ada85-5e96-4020-b4b3-3cd272ac0861"

# Отправлять уведомление на почту mailto: beckkhan@mail.ru если сборка упала
notifications:
  email:
    recipients:
      -mailto: beckkhan@mail.ru
    on_success: never # default: change
    on_failure: always # default: always